# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true
os:
  - linux
  - osx

env:
  global: RGL_USE_NULL=TRUE

r_check_args: "--as-cran --install-args=--build"

before_install:
  - wget -O travis_helpers.sh http://bit.ly/travis_helpers
  - source travis_helpers.sh
  - rm travis_helpers.sh
  - PACKAGE_NAME=`package_name`
  - PACKAGE_DIRECTORY=`basename ${PWD}`

apt_packages:
  - texinfo

after_success:
  - Rscript -e 'covr::coveralls(type = "all")'
